-- Add geolocation columns to agents table
ALTER TABLE agents ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS country_code TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
